export const elementsLocators={
    elements: "//div[@class='card-body'][h5[text()='Elements']]",
    textBox: "//span[@class='text'][text()='Text Box']",
    checkBox: "//span[@class='text'][text()='Check Box']",
    radioButton: "//span[@class='text'][text()='Radio Button']",
    webTables: "//span[@class='text'][text()='Web Tables']" ,
    buttons: "//span[@class='text'][text()='Buttons']",
    links: "//span[@class='text'][text()='Links']",
    brokenLinks: "//span[@class='text'][text()='Broken Links - Images']",
    uploadDownload: "//span[@class='text'][text()='Upload and Download']",
    dynamicProperties: "//span[@class='text'][text()='Dynamic Properties']",
    practiceForm: "//span[@class='text'][text()='Practice Form']",
    browserWindows: "//span[@class='text'][text()='Browser Windows']",
    alerts: "//span[@class='text'][text()='Alerts']",
    frames: "//span[@class='text'][text()='Frames']",
    nestedFrames: "//span[@class='text'][text()='Nested Frames']",
    modalDialogs: "//span[@class='text'][text()='Modal Dialogs']",
    accordian: "//span[@class='text'][text()='Accordian']",
    autoComplete: "//span[@class='text'][text()='Auto Complete']",
    datePicker: "//span[@class='text'][text()='Date Picker']",
    slider: "//span[@class='text'][text()='Slider']",
    progressBar: "//span[@class='text'][text()='Progress Bar']",
    tabs: "//span[@class='text'][text()='Tabs']",
    toolTips: "//span[@class='text'][text()='Tool Tips']",
    menu: "//span[@class='text'][text()='Menu']",
    selectMenu: "//span[@class='text'][text()='Select Menu']",
    sortable: "//span[@class='text'][text()='Sortable']",
    selectable: "//span[@class='text'][text()='Selectable']",
    resizable: "//span[@class='text'][text()='Resizable']",
    droppable: "//span[@class='text'][text()='Droppable']",
    dragabble: "//span[@class='text'][text()='Dragabble']",
    login: "//span[@class='text'][text()='Login']",
    bookStore: "//span[@class='text'][text()='Book Store']",
    profile: "//span[@class='text'][text()='Profile']",
    bookStoreAPI: "//span[@class='text'][text()='Book Store API']",

    textBoxButton: "//span[@class='text'][text()='Text Box']",
    ChecktBoxButton: "//span[@class='text'][text()='Check Box']",
    textBoxText: "//h1[@class='text-center']",
    checkBoxText: "//h1[@class='text-center']",

    fullNameInput: "//input[@id='userName']",
    EmailInput: "//input[@id='userEmail']",
    CurrentAdressInput: "//textarea[@id='currentAddress']",
    PermanentAddressInput: "//textarea[@id='permanentAddress']",
    submitButton: "//button[@id='submit']",

    savedName: "//p[@id='name']",
    savedEmail: "//p[@id='email']",
    savedCAddress: "//p[@id='currentAddress']",
    savedPAddress: "//p[@id='permanentAddress']",
 
    errorEmail: "//input[@id='userEmail']",

    homeButton: "//label[@for='tree-node-home']",
    desktopButton: "//label[@for='tree-node-desktop']",
    documentsButton: "//label[@for='tree-node-documents']",
    downloadsButton: "//label[@for='tree-node-downloads']",
    homeText: "#result",
    toogleHome: "//button[@aria-label='Toggle']",

    
   
}